version: "3.2"

services:
  filebeat:
    container_name: beat-filebeat
    hostname: "filebeat-server"
    user: root
    image: docker.elastic.co/beats/filebeat:7.15.1
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./mylog:/usr/share/filebeat/mylog
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    network_mode: "host"
    command: filebeat -e -strict.perms=false -E output.elasticsearch.hosts=localhost:9200 -E output.elasticsearch.username=elastic -E output.elasticsearch.password=changeme
    restart: on-failure